version: '3'

services:
    node_exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node_exporter
      command:
        - '--path.rootfs=/host'
        - '--collector.filesystem.mount-points-exclude=^/(host|etc)($$|/)'
        - '--log.level=debug'
      network_mode: host
      pid: host
      restart: unless-stopped
      ports:
        - '9100:9100'
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/host:ro